Repository carflor/movieReviewer, pull requests merged in 2020-07, with the labels that each got.

#17 Feature/it2
  package.json
  src/App.js
  src/App.test.js
  src/Components/Body.js
  src/Components/LogInForm.js
  src/Components/MovieCard.js
  src/Components/Nav.js
Labels: enhancement

#18 Feature/logoutandtests
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/Components/Body.js
  src/Components/Body.test.js
  src/Components/MovieCard.js
  src/Components/MovieCard.test.js
  src/Components/MoviePage.css
  src/Components/MoviePage.js
  src/Components/MoviePage.test.js
  src/Components/Nav.js
  src/Components/Nav.test.js
Labels: enhancement

#29 Feature/it3
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/App.test.js
  src/Assets/angle-double-left-solid.svg
  src/Assets/goldenstaricon.png
  src/Assets/star-golden.svg
  src/Assets/star-regular.svg
  src/Components/Body.css
  src/Components/Body.js
  src/Components/LogInForm.js
  src/Components/MovieCard.css
  src/Components/MovieCard.js
  src/Components/MoviePage.css
  src/Components/MoviePage.js
  src/Components/Nav.css
  src/Components/Nav.js
  src/Components/Nav.test.js
  src/Components/_Body.scss
  src/Components/_LogInForm.scss
  src/Components/_MovieCard.scss
  src/Components/_MoviePage.scss
  src/Components/_Nav.scss
  src/_variables.scss
  src/base.scss
  src/index.js
  src/logo.svg
Labels: bug, enhancement

#30 Feature/stylingandratingsystem
  src/App.js
  src/Components/LogInForm.js
  src/Components/MoviePage.js
  src/Components/Nav.js
  src/Components/_LogInForm.scss
  src/Components/_MovieCard.scss
  src/Components/_MoviePage.scss
  src/index.js
  src/index.scss
Labels: enhancement

#33 Feature/it5
  src/App.js
  src/Assets/goldenstaricon.png
  src/Components/LogInForm.js
  src/Components/MovieCard.js
  src/Components/MoviePage.js
  src/Components/_MovieCard.scss
  src/Components/_MoviePage.scss
  src/Components/_Nav.scss
  src/index.scss
Labels: enhancement

#41 Feature/detailing
  src/App.js
  src/Components/MovieCard.js
  src/Components/MoviePage.js
  src/Components/_Body.scss
  src/Components/_MovieCard.scss
  src/Components/_MoviePage.scss
  src/Components/_Nav.scss
Labels: bug

#48 Feature/testing
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/Components/LogInForm.js
  src/Components/LogInForm.test.js
  src/Components/MovieCard.js
  src/Components/MovieCard.test.js
  src/Components/MoviePage.js
  src/Components/Nav.test.js
  src/Components/_LogInForm.scss
  src/Components/_MovieCard.scss
  src/apiCalls.js
Labels: enhancement

#50 Refactor for react router use for app, fix styling issues with Link
  src/App.js
  src/Components/LogInForm.js
  src/Components/MovieCard.js
  src/Components/MoviePage.js
  src/Components/Nav.js
  src/Components/_Nav.scss
  src/index.js
Labels: enhancement

#52 Feature/testing
  src/App.js
  src/App.test.js
  src/Components/LogInForm.test.js
  src/Components/MovieCard.test.js
  src/Components/MoviePage.js
  src/Components/MoviePage.test.js
  src/Components/Nav.test.js
  src/apiCalls.js
Labels: enhancement

#54 Feature/ratingtesting
  src/App.test.js
  src/Components/MoviePage.js
  src/apiCalls.js
Labels: enhancement

#56 Feature/react router
  src/App.js
  src/Components/Body.test.js
  src/Components/LogInForm.js
  src/Components/LogInForm.test.js
  src/Components/MovieCard.test.js
  src/Components/MoviePage.test.js
  src/Components/Nav.js
  src/Components/Nav.test.js
  src/Components/_LogInForm.scss
  src/apiCalls.js
Labels: enhancement

#59 Feature/comments
  src/App.js
  src/App.test.js
  src/Components/Body.js
  src/Components/Body.scss
  src/Components/CommentCard.js
  src/Components/LogInForm.js
  src/Components/LogInForm.scss
  src/Components/MovieCard.js
  src/Components/MovieCard.scss
  src/Components/MoviePage.js
  src/Components/MoviePage.scss
  src/Components/Nav.js
  src/Components/Nav.scss
  src/Components/_MoviePage.scss
  src/apiCalls.js
  src/index.scss
Labels: enhancement

#60 Feature/trailer
  src/Components/MoviePage.js
  src/apiCalls.js
Labels: bug, enhancement

#63 Fix duplication submit bug, fix empty comment bug
  src/Components/MoviePage.js
  src/apiCalls.js
Labels: enhancement

#65 Feature/favoritingmovies
  src/App.js
  src/App.scss
  src/Assets/heart-outline.png
  src/Assets/heart-red.png
  src/Components/Body.js
  src/Components/Body.scss
  src/Components/LogInForm.js
  src/Components/LogInForm.scss
  src/Components/MovieCard.js
  src/Components/MovieCard.scss
  src/Components/MoviePage.js
  src/Components/Nav.js
  src/Components/Nav.scss
  src/_variables.scss
  src/apiCalls.js
  src/index.scss
Labels: enhancement

#67 Feature/refactortests
  package-lock.json
  package.json
  src/App.test.js
  src/Components/LogInForm.js
  src/Components/MoviePage.js
  src/Components/MoviePage.scss
  src/Components/Nav.scss
  src/Components/Nav.test.js
Labels: enhancement
